# Generated by Django 3.2.3 on 2022-12-11 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_meals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meals',
            new_name='Meal',
        ),
    ]
